name: dress-me-up
services:
  api:
    build:
      context: ../../..
      dockerfile: app/backend/api/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ../../.env

#  mobile:
#    build:
#      context: ../../..
#      dockerfile: app/mobile/Dockerfile
#    ports:
#      - "8082:8081"
#      - "19000:19000"
#    volumes:
#      - ../../../app/mobile:/app
#      - mobile_node_modules:/app/node_modules
#    command: npm start
#
#volumes:
#  mobile_node_modules:
#    driver: local
